# Generated by Django 4.2.6 on 2023-10-27 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sim_site", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirisedtmdata",
            name="CORRELATION_LENGTH",
        ),
        migrations.RemoveField(
            model_name="hirisedtmdata",
            name="ROOT_MEAN_SQUARE_HEIGHT",
        ),
    ]
