# Generated by Django 4.2.6 on 2023-10-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sim_site", "0002_remove_hirisedtmdata_correlation_length_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SIM3292_Global_Geology",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("unit", models.CharField(max_length=10, verbose_name="分类缩写")),
                ("unit_name", models.CharField(max_length=50, verbose_name="分类名称")),
                ("description", models.CharField(max_length=150, verbose_name="分类描述")),
                (
                    "ADDITIONAL_CHARACTERISTICS",
                    models.CharField(max_length=150, verbose_name="附加特征"),
                ),
                ("interpretation", models.CharField(max_length=150, verbose_name="解释")),
                ("RGB", models.CharField(max_length=50, verbose_name="颜色")),
                ("main_unit", models.CharField(max_length=50, verbose_name="主分类")),
                (
                    "main_unit_desc",
                    models.CharField(max_length=150, verbose_name="主分类描述"),
                ),
                ("corresponding_value", models.FloatField(verbose_name="对应值")),
            ],
            options={
                "verbose_name": "SIM3292全球地质数据",
                "verbose_name_plural": "SIM3292全球地质数据",
                "db_table": "sim3292_global_geology",
                "ordering": ["id"],
            },
        ),
    ]
