# Generated by Django 4.2.6 on 2023-10-28 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sim_site", "0003_sim3292_global_geology"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sim3292_global_geology",
            old_name="ADDITIONAL_CHARACTERISTICS",
            new_name="additional_characteristics",
        ),
    ]
