# Generated by Django 4.2.6 on 2023-10-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sim_site",
            "0004_rename_additional_characteristics_sim3292_global_geology_additional_characteristics",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sim3292_global_geology",
            name="additional_characteristics",
            field=models.CharField(max_length=300, verbose_name="附加特征"),
        ),
        migrations.AlterField(
            model_name="sim3292_global_geology",
            name="description",
            field=models.CharField(max_length=300, verbose_name="分类描述"),
        ),
        migrations.AlterField(
            model_name="sim3292_global_geology",
            name="interpretation",
            field=models.CharField(max_length=300, verbose_name="解释"),
        ),
    ]
