# Generated by Django 4.2.6 on 2023-10-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sim_site",
            "0006_alter_sim3292_global_geology_additional_characteristics_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sim3292_global_geology",
            name="main_unit",
            field=models.CharField(max_length=100, verbose_name="主分类"),
        ),
        migrations.AlterField(
            model_name="sim3292_global_geology",
            name="unit_name",
            field=models.CharField(max_length=100, verbose_name="分类名称"),
        ),
    ]
