# Generated by Django 4.2.6 on 2023-10-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sim_site", "0008_alter_sim3292_global_geology_unit_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sim3292_global_geology",
            name="additional_characteristics",
            field=models.CharField(max_length=1000, verbose_name="附加特征"),
        ),
        migrations.AlterField(
            model_name="sim3292_global_geology",
            name="description",
            field=models.CharField(max_length=1000, verbose_name="分类描述"),
        ),
        migrations.AlterField(
            model_name="sim3292_global_geology",
            name="interpretation",
            field=models.CharField(max_length=1000, verbose_name="解释"),
        ),
        migrations.AlterField(
            model_name="sim3292_global_geology",
            name="main_unit_desc",
            field=models.CharField(max_length=1000, verbose_name="主分类描述"),
        ),
        migrations.AlterField(
            model_name="sim3292_global_geology",
            name="unit_name",
            field=models.CharField(max_length=100, verbose_name="分类名称"),
        ),
    ]
