# Generated by Django 4.2.6 on 2023-10-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sim_site",
            "0009_alter_sim3292_global_geology_additional_characteristics_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SharadRDRTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("VOLUME_ID", models.CharField(max_length=20, verbose_name="卷ID")),
                (
                    "RGRAM_FILE_SPECIFICATION_NAME",
                    models.CharField(max_length=100, verbose_name="RGRAM文件相对路径"),
                ),
                (
                    "GEOM_FILE_SPECIFICATION_NAME",
                    models.CharField(max_length=100, verbose_name="GEOM文件相对路径"),
                ),
                ("PRODUCT_ID", models.CharField(max_length=50, verbose_name="产品ID")),
                ("PRODUCT_CREATION_TIME", models.DateTimeField(verbose_name="产品创建时间")),
                ("ORBIT_NUMBER", models.IntegerField(verbose_name="轨道号")),
                ("START_TIME", models.DateTimeField(verbose_name="开始时间")),
                ("STOP_TIME", models.DateTimeField(verbose_name="结束时间")),
                (
                    "MRO_START_SUB_SPACECRAFT_LATITUDE",
                    models.FloatField(verbose_name="MRO：子航天器起始纬度"),
                ),
                (
                    "MRO_STOP_SUB_SPACECRAFT_LATITUDE",
                    models.FloatField(verbose_name="MRO：子航天器结束纬度"),
                ),
                (
                    "MRO_START_SUB_SPACECRAFT_LONGITUDE",
                    models.FloatField(verbose_name="MRO：子航天器起始经度"),
                ),
                (
                    "MRO_STOP_SUB_SPACECRAFT_LONGITUDE",
                    models.FloatField(verbose_name="MRO：子航天器结束经度"),
                ),
            ],
            options={
                "verbose_name": "SHARAD RDR数据",
                "verbose_name_plural": "SHARAD RDR数据",
                "db_table": "sharad_rdr_table",
                "ordering": ["id"],
            },
        ),
    ]
